version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/ezcater
    docker:
      - image: circleci/ruby:2.5.7
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "mail_allowed.gemspec" }}
            - ruby-cache-{{ arch }}-{{ .Branch }}-
            - ruby-cache-

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Bundle install dependencies
      - run: gem install bundler -v 1.17.3 --no-document
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle clean --force

      # Store bundle cache
      - save_cache:
          key: ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "mail_allowed.gemspec" }}
          paths:
            - vendor/bundle

      # Run Rubocop
      # - run:
      #     name: RuboCop
      #     command: bundle exec rubocop

      - run:
          name: rspec
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --format RspecJunitFormatter --format progress
            ./cc-test-reporter after-build -t simplecov || exit 0
