name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
    timeout-minutes: 10
    env:
      BUNDLE_EZCATER__JFROG__IO: ${{ secrets.BUNDLE_EZCATER__JFROG__IO }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec
